language: python
python:
  - "3.6"
install:
  - pip install cython
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
script:
  - nose2 -v gendis
  - python -m doctest -v gendis/genetic.py